"""Tests for check_9_review_valve - Stage-5 Check 9."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from tests.support import DEFAULT_PROJECT_KEY, seed_project_config
from woof import state
from woof.checks import CheckContext
from woof.checks.runners.check_9_review_valve import (
    _is_end_of_epic,
    check_9_review_valve_runner,
)
from woof.gate.write import write_gate_from_check_result


def _work_unit(work_unit_id: str, state: str) -> dict:
    return {"id": work_unit_id, "state": state}


def _ctx(repo_root: Path, stories: list[dict], work_unit_id: str = "S2") -> CheckContext:
    epic_dir = state.epic_dir(DEFAULT_PROJECT_KEY, 1)
    epic_dir.mkdir(parents=True, exist_ok=True)
    return CheckContext(
        epic_id=1,
        work_unit_id=work_unit_id,
        project_key=DEFAULT_PROJECT_KEY,
        repo_root=repo_root,
        epic_dir=epic_dir,
        plan={"epic_id": 1, "goal": "test", "work_units": stories},
        critique=None,
    )


def _seed_config(
    *,
    every_n: int = 2,
    end_of_epic: bool = False,
    max_non_generated_changed_lines: int | None = None,
) -> None:
    """Declare the review valve, and the review-size guard only when asked for.

    ``max_non_generated_changed_lines`` of None removes ``[checks.review_size]``,
    which is how a project declares no review-size guard at all.
    """

    review_size: dict[str, Any] | None = (
        None
        if max_non_generated_changed_lines is None
        else {"max_non_generated_changed_lines": max_non_generated_changed_lines}
    )
    seed_project_config(
        {
            "review_valve": {"every_n_work_units": every_n, "end_of_epic": end_of_epic},
            "checks": {"floor": ["review-valve"], "review_size": review_size},
        }
    )


def _write_critique(epic_dir: Path, work_unit_id: str, findings: list[dict]) -> None:
    critique_dir = epic_dir / "critique"
    critique_dir.mkdir(parents=True, exist_ok=True)
    severity = "minor" if findings else "info"
    critique_dir.joinpath(f"work-unit-{work_unit_id}.md").write_text(
        "---\n"
        "target: work_unit\n"
        f"target_id: {work_unit_id}\n"
        f"severity: {severity}\n"
        "timestamp: '2026-01-01T00:00:00Z'\n"
        "harness: test\n"
        f"findings: {json.dumps(findings)}\n"
        "---\n"
    )


def _git(repo_root: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo_root, check=True, capture_output=True)


def _init_git(repo_root: Path) -> None:
    _git(repo_root, "init")
    _git(repo_root, "config", "user.email", "test@example.com")
    _git(repo_root, "config", "user.name", "Test")


def _stage_file(repo_root: Path, rel_path: str, text: str) -> None:
    path = repo_root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    _git(repo_root, "add", "--", rel_path)


def test_threshold_due_with_minor_findings_fails(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=False)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F1", "severity": "minor", "summary": "Follow-up refactor is worth review"}],
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "every 2 work units" in outcome.summary
    assert "S2/F1: Follow-up refactor is worth review" in (outcome.evidence or "")


def test_review_size_guard_counts_only_non_generated_changed_lines(tmp_path: Path) -> None:
    _init_git(tmp_path)
    _seed_config(every_n=99, end_of_epic=False, max_non_generated_changed_lines=2)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _stage_file(tmp_path, "src/app.py", "one\ntwo\n")
    _stage_file(
        tmp_path,
        "generated/report.py",
        "# Code generated by fixture. DO NOT EDIT.\n" + "\n".join(f"line {i}" for i in range(20)),
    )

    outcome = check_9_review_valve_runner(ctx)

    assert outcome.ok
    assert "2 non-generated changed line(s)" in outcome.summary
    assert "excluded 21 generated changed line(s)" in outcome.summary
    assert "generated/report.py: 21 generated changed line(s) excluded" in (outcome.evidence or "")


def test_review_size_guard_fails_when_non_generated_changed_lines_exceed_policy(
    tmp_path: Path,
) -> None:
    _init_git(tmp_path)
    _seed_config(every_n=99, end_of_epic=False, max_non_generated_changed_lines=2)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _stage_file(tmp_path, "src/app.py", "one\ntwo\nthree\n")
    _stage_file(
        tmp_path,
        "generated/files.py",
        "# @generated\n" + "\n".join(f"generated_{i} = 1" for i in range(19)),
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "3 non-generated changed line(s) exceed policy threshold 2" in outcome.summary
    assert "src/app.py: 3 non-generated changed line(s)" in (outcome.evidence or "")
    assert "generated/files.py: 20 generated changed line(s) excluded" in (outcome.evidence or "")


def test_review_size_guard_reports_all_generated_file_classes(tmp_path: Path) -> None:
    _init_git(tmp_path)
    (tmp_path / ".gitattributes").write_text("linguist/*.json linguist-generated=true\n")
    _seed_config(every_n=99, end_of_epic=False, max_non_generated_changed_lines=1)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _stage_file(tmp_path, "linguist/data.json", '{"generated": true}\n')
    _stage_file(tmp_path, "src/generated_client.py", "# @generated\nvalue = 1\n")

    outcome = check_9_review_valve_runner(ctx)

    assert outcome.ok
    evidence = outcome.evidence or ""
    assert (
        "linguist/data.json: 1 generated changed line(s) excluded (linguist-generated)" in evidence
    )
    assert (
        "src/generated_client.py: 2 generated changed line(s) excluded (generated header)"
        in evidence
    )


def test_end_of_epic_due_with_minor_findings_fails(tmp_path: Path) -> None:
    _seed_config(every_n=5, end_of_epic=True)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F1", "severity": "minor", "summary": "End-of-epic polish note"}],
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "end of epic" in outcome.summary


def test_end_of_epic_due_when_only_later_stories_are_abandoned(tmp_path: Path) -> None:
    # A later work unit that is `abandoned` is terminal and will never be worked, so
    # the current work unit is still end-of-epic. The valve must fire on its minor
    # findings rather than be suppressed by the abandoned tail. every_n is set
    # high so only the end-of-epic trigger can fire.
    _seed_config(every_n=5, end_of_epic=True)
    ctx = _ctx(
        tmp_path,
        [
            _work_unit("S1", "done"),
            _work_unit("S2", "in_progress"),
            _work_unit("S3", "abandoned"),
        ],
    )
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F1", "severity": "minor", "summary": "End-of-epic polish note"}],
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "end of epic" in outcome.summary


def test_is_end_of_epic_treats_abandoned_tail_as_terminal() -> None:
    # An abandoned tail work unit is terminal: the current unit is still end-of-epic.
    abandoned_tail = [
        _work_unit("S1", "done"),
        _work_unit("S2", "in_progress"),
        _work_unit("S3", "abandoned"),
    ]
    assert _is_end_of_epic(abandoned_tail, "S2") is True
    # A pending tail work unit still needs work: not end-of-epic.
    pending_tail = [
        _work_unit("S1", "done"),
        _work_unit("S2", "in_progress"),
        _work_unit("S3", "pending"),
    ]
    assert _is_end_of_epic(pending_tail, "S2") is False


def test_due_boundary_with_no_minor_findings_passes(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=True)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _write_critique(ctx.epic_dir, "S2", [])

    outcome = check_9_review_valve_runner(ctx)

    assert outcome.ok
    assert outcome.severity == "info"
    assert "no minor critique findings" in outcome.summary


def test_already_review_gated_boundary_passes(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=False)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F1", "severity": "minor", "summary": "Already surfaced"}],
    )
    ctx.epic_dir.joinpath("epic.jsonl").write_text(
        json.dumps(
            {
                "event": "review_gate_opened",
                "work_unit_id": "S2",
                "triggered_by": ["check_9_review_valve"],
            }
        )
        + "\n"
    )

    outcome = check_9_review_valve_runner(ctx)

    assert outcome.ok
    assert "already been review-gated" in outcome.summary


def test_retried_boundary_re_arms_valve(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=False)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F2", "severity": "minor", "summary": "Fresh finding after retry"}],
    )
    # The valve already fired and opened a review gate at S2, but retry_work_unit
    # then reset S2 and appended work_unit_retried. The stale review_gate_opened must
    # not suppress a new gate once the retried work unit produces a fresh critique.
    ctx.epic_dir.joinpath("epic.jsonl").write_text(
        json.dumps(
            {
                "event": "review_gate_opened",
                "work_unit_id": "S2",
                "triggered_by": ["check_9_review_valve"],
            }
        )
        + "\n"
        + json.dumps({"event": "work_unit_retried", "work_unit_id": "S2"})
        + "\n"
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "S2/F2: Fresh finding after retry" in (outcome.evidence or "")


def test_retried_boundary_keeps_prior_sibling_gated_when_clean(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=False)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    # The S2 review gate bundled S1's minor finding. retry_work_unit on S2 reset S2
    # and deleted its critique; the retried run produced a clean S2 critique. The
    # already-gated S1 finding must not re-open a gate now that S2 has nothing new.
    _write_critique(
        ctx.epic_dir,
        "S1",
        [{"id": "F1", "severity": "minor", "summary": "Already gated at the S2 review"}],
    )
    _write_critique(ctx.epic_dir, "S2", [])
    ctx.epic_dir.joinpath("epic.jsonl").write_text(
        json.dumps(
            {
                "event": "review_gate_opened",
                "work_unit_id": "S2",
                "triggered_by": ["check_9_review_valve"],
            }
        )
        + "\n"
        + json.dumps({"event": "work_unit_retried", "work_unit_id": "S2"})
        + "\n"
    )

    outcome = check_9_review_valve_runner(ctx)

    assert outcome.ok
    assert outcome.severity == "info"
    assert "no minor critique findings" in outcome.summary


def test_retried_boundary_gates_only_fresh_finding(tmp_path: Path) -> None:
    _seed_config(every_n=2, end_of_epic=False)
    ctx = _ctx(tmp_path, [_work_unit("S1", "done"), _work_unit("S2", "in_progress")])
    # Same setup as above, but the retried S2 critique surfaces a new minor
    # finding. The new gate must carry only that fresh finding, not the S1 finding
    # that was already bundled into the previous review gate.
    _write_critique(
        ctx.epic_dir,
        "S1",
        [{"id": "F1", "severity": "minor", "summary": "Already gated at the S2 review"}],
    )
    _write_critique(
        ctx.epic_dir,
        "S2",
        [{"id": "F3", "severity": "minor", "summary": "New issue from the retried run"}],
    )
    ctx.epic_dir.joinpath("epic.jsonl").write_text(
        json.dumps(
            {
                "event": "review_gate_opened",
                "work_unit_id": "S2",
                "triggered_by": ["check_9_review_valve"],
            }
        )
        + "\n"
        + json.dumps({"event": "work_unit_retried", "work_unit_id": "S2"})
        + "\n"
    )

    outcome = check_9_review_valve_runner(ctx)

    assert not outcome.ok
    assert outcome.severity == "minor"
    assert "S2/F3: New issue from the retried run" in (outcome.evidence or "")
    assert "F1" not in (outcome.evidence or "")
    assert "S1" not in (outcome.evidence or "")


def test_check_9_gate_is_written_as_review_gate(tmp_path: Path) -> None:
    epic_dir = state.epic_dir(DEFAULT_PROJECT_KEY, 1)
    epic_dir.mkdir(parents=True, exist_ok=True)
    check_result = state.check_result_path(DEFAULT_PROJECT_KEY, 1)
    check_result.write_text(
        json.dumps(
            {
                "ok": False,
                "stage": 5,
                "epic_id": 1,
                "work_unit_id": "S2",
                "triggered_by": ["check_9_review_valve"],
                "checks": [
                    {
                        "id": "check_9_review_valve",
                        "ok": False,
                        "severity": "minor",
                        "summary": "review due",
                        "evidence": "S2/F1: review this",
                        "paths": [],
                        "command": None,
                        "exit_code": None,
                    }
                ],
            }
        )
    )

    gate_path = write_gate_from_check_result(check_result, None, DEFAULT_PROJECT_KEY, 1, "S2")

    gate_text = gate_path.read_text()
    assert "type: review_gate" in gate_text
    events = [json.loads(line) for line in epic_dir.joinpath("epic.jsonl").read_text().splitlines()]
    assert events[-1]["event"] == "review_gate_opened"
    assert events[-1]["gate_type"] == "review_gate"
